"""Output file management for kea-dhcp-config-generator.

Filename modes:
  default     kea-{protocol}-YYYYMMDD-HHMM.conf  (timestamped; safe for repeated runs)
  --overwrite kea-{protocol}.conf                 (overwrites any existing file)

Analysis report file modes:
  default     kea-analysis-YYYYMMDD-HHMM.txt     (timestamped; safe for repeated runs)
  --overwrite kea-analysis.txt                    (overwrites any existing file)
"""

import json
from datetime import datetime
from pathlib import Path

from kea_dhcp_config_generator import __version__

_HEADER_KEY = "_kea-config-generator"


def write(
    config_dict: dict,
    protocol: str,
    output_dir: Path = Path("."),
    *,
    overwrite: bool = False,
    timestamp: datetime | None = None,
) -> Path:
    """Write a Kea config dict to a file and return the written path.

    Args:
        config_dict: The built Kea config dict (e.g. from builders.dhcp4.build()).
        protocol:    "dhcp4" or "dhcp6".
        output_dir:  Directory to write the file into. Defaults to CWD.
        overwrite:   Write to canonical filename (kea-{protocol}.conf); overwrite
                     any existing file. Default False produces a timestamped filename.
        timestamp:   Override the timestamp (injectable for deterministic tests).
                     Defaults to datetime.now() at call time.

    Returns:
        Path to the written file.
    """
    if timestamp is None:
        timestamp = datetime.now()

    if overwrite:
        filename = f"kea-{protocol}.conf"
    else:
        ts_str = timestamp.strftime("%Y%m%d-%H%M")
        filename = f"kea-{protocol}-{ts_str}.conf"

    output_path = output_dir / filename

    document = {
        _HEADER_KEY: {
            "version": __version__,
            "warning": (
                "This file is auto-generated by kea-dhcp-config-generator. "
                "Do not edit directly."
            ),
        },
        **config_dict,
    }

    output_path.write_text(
        json.dumps(document, indent=2, ensure_ascii=True, sort_keys=False) + "\n",
        encoding="utf-8",
    )

    return output_path


def write_analysis(
    report: str,
    output_dir: Path = Path("."),
    *,
    overwrite: bool = False,
    timestamp: datetime | None = None,
) -> Path:
    """Write an analysis report to a file and return the written path.

    Args:
        report:     The plain-text report string (from analysis.generate_report).
        output_dir: Directory to write the file into. Defaults to CWD.
        overwrite:  Write to canonical filename (kea-analysis.txt); overwrite
                    any existing file. Default False produces a timestamped filename.
        timestamp:  Override the timestamp (injectable for deterministic tests).
                    Defaults to datetime.now() at call time.

    Returns:
        Path to the written file.
    """
    if timestamp is None:
        timestamp = datetime.now()

    if overwrite:
        filename = "kea-analysis.txt"
    else:
        ts_str = timestamp.strftime("%Y%m%d-%H%M")
        filename = f"kea-analysis-{ts_str}.txt"

    output_path = output_dir / filename
    output_path.write_text(report, encoding="utf-8")

    return output_path
